### ISSUE TITLE
How to add new font for local testing

### ISSUE THREAD

**Issue by tlyeung** [tikui/tikui.org#27]
Hi.

I would like to know how to apply the new font, i.e. in file type ".ttf", to local testing (```npm run serve```)?

How should I config it?

Thanks.

**Comment by Gnuk** [comment]
Hi,

Sorry for the late answer:

From a tikui project, the structure use standard SCSS so you can use css fonts.

You just have to put your font and the css in a folder inside the source with a valid link to the font (for example is you put a relative link and you include your scss file from another part of the project, the link will be relative to the inclusion and may not work).

Then you can try to launch it with `npm run serve`

But in tikui.org, the style is inside the [tikuidoc-tikui](https://github.com/tikui/tikuidoc-tikui) module, so you have to check how the documentation work : To test it locally, you have to use npm link.

Don't hesitate to answer this message if it's not clear, because [tikui.org](tikui.org) is the website based on the Tikui framework but with the style from an external module (it is the way for me to not have a cyclic dependency for the style).
